### ISSUE TITLE
Can't send DICOM file to dicom server

### ISSUE THREAD

**Issue by ynakanishi1985** [knopkem/dicomweb-pacs#32]
Hello, thank you so much for your prompt update about character set for multi language for patient info.

Now, I have another issue.
We can't send dicom file from my Orthanc to server.

Power shell shows as below ;
"W: No matching AET found for AET:DICOMWEB_PACS" 
I don't know which setting or configuration is wrong.

You can check captured screen as below ;
https://youtu.be/49vjmce6-d0

Would you kindly advise me ?

**Comment by ynakanishi1985** [comment]
A week ago, I could send to server from my orthanc.

**Comment by knopkem** [comment]
There was indeed a missing step when initializing the server which is now fixed in the latest version.
Note that while you should now be able to push/query/echo dicomweb-pacs again, it is only because of the property:
permissiveMode=true
You won't be able to C-Move on it as you did not specify ORTHANC as a peer.
So a better approach is to replace peers with:
```
peers: [
      {
        aet: "ORTHANC",
        ip: "127.0.0.1",
        port: "4242"
      }],
```
...and to turn of permissiveMode

**Comment by ynakanishi1985** [comment]
I have tried nad now everything is fine !!
