### ISSUE TITLE
dicomVirtual printing

### ISSUE THREAD

**Issue by CloudWoR** [knopkem/dicomweb-pacs#6]
hi, I want to realize the DICOM virtual printing server, that is: the server as a virtual film printer, can use this library to realize?

**Comment by knopkem** [comment]
Hi, currently there is nothing implemented relating to DICOM printing. The underlying native library (using DCMTK toolkit): https://github.com/knopkem/dicom-dimse-native/releases could be modified to implement a print server, see https://support.dcmtk.org/docs/dcmprscp.html, but might not be straightforward to do.

**Comment by CloudWoR** [comment]
thank you, 
If there is a problem, can I ask you?

**Comment by knopkem** [comment]
Hi, can you explain a bit more the workflow and what you want to achieve. The thing is that DCMTK only provides a part of what a virtual print server should do (mainly only receiving print jobs via dicom). Also since DCMTK is c++ you need to ask yourself if you really need nodejs wrapping or if building a standalone c++ server would be enough.

**Comment by CloudWoR** [comment]
I need this program to receive the film sent by DICOM workstation, then store it in the database, and send it to the film printer through this program at some time in the future
